version: "3"

services:
  dns:
    container_name: dns
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dnss:latest
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      TZ: "America/Chigago"
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./pihole-log:/var/log/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - dns
